<?php
/**
 * Title: Header
 * Slug: lexcollect/header
 * Categories: header
 * Block Types: core/template-part/header
 * Inserter: no
 * Viewport Width: 1400
 * Description: Logo lockup, main menu, Log in link and the Book a call button.
 *
 * Generated by scripts/build-wordpress-theme.py from the React marketing site.
 * Edit the copy in src/pages and rebuild, or edit this HTML block in WordPress.
 *
 * @package LexCollect
 */

?>
<!-- wp:html -->
<header class="site-header"><div class="container"><a class="brand" aria-label="LexCollect home" href="<?php echo esc_url( home_url( '/' ) ); ?>"><svg viewBox="0 0 686 759" aria-hidden="true"><path fill="#FFFFFF" d="M0 0H160V609H686V759H0Z"></path><path fill="#3DD9C7" d="M203 0H686V227H559V127H330V439H559V360H686V567H203Z"></path></svg><span class="wordmark"><span class="lex">Lex</span><span class="collect">Collect</span></span></a><button type="button" class="nav-toggle" aria-expanded="false" aria-controls="site-nav"><span></span><span class="visually-hidden">Menu</span></button><nav class="nav" id="site-nav" aria-label="Main"><ul><li><a href="<?php echo esc_url( lexcollect_page_url( 'platform' ) ); ?>">Platform</a></li><li><a href="<?php echo esc_url( lexcollect_page_url( 'results' ) ); ?>">Results</a></li><li><a href="<?php echo esc_url( lexcollect_page_url( 'about' ) ); ?>">About</a></li><li><a href="<?php echo esc_url( lexcollect_page_url( 'blog' ) ); ?>">Blog</a></li><li><a href="<?php echo esc_url( lexcollect_page_url( 'contact' ) ); ?>">Contact</a></li><li><a href="<?php echo esc_url( LEXCOLLECT_APP_LOGIN_URL ); ?>">Log in</a></li></ul><a class="btn btn--primary btn--sm" href="<?php echo esc_url( lexcollect_booking_url() ); ?>">Book a call</a></nav></div></header>
<!-- /wp:html -->
