<?php
/**
 * Title: Contact page
 * Slug: lexcollect/page-contact
 * Categories: lexcollect-pages
 * Block Types: core/post-content
 * Post Types: page
 * Viewport Width: 1400
 * Description: Call request form, what happens next, and common questions.
 *
 * Generated by scripts/build-wordpress-theme.py from the React marketing site.
 * Edit the copy in src/pages and rebuild, or edit this HTML block in WordPress.
 *
 * @package LexCollect
 */

?>
<!-- wp:html -->
<section class="page-hero"><div class="container"><p class="breadcrumb"><a href="<?php echo esc_url( home_url( '/' ) ); ?>">Home</a> / Contact</p><p class="eyebrow">Contact</p><h1>Book a call about your firm&#x27;s receivables.</h1><p class="lead">Tell us about your firm and the systems you use. We&#x27;ll show you where money is stuck, what each account is worth, and which clients one message would bring back.</p></div></section><section class="section"><div class="container"><div class="split split--wide-left">
<!-- /wp:html -->

<!-- wp:shortcode -->
[lexcollect_contact heading="Request a call"]
<!-- /wp:shortcode -->

<!-- wp:html -->
<aside><p class="eyebrow">What happens next</p><ol class="next-steps"><li><b>We reply within one business day</b><span>To set up a time that works for your team.</span></li><li><b>We walk through your systems</b><span>Which client-management, payment and accounting tools you run, and where the money seems to go missing.</span></li><li><b>You see what&#x27;s fixable</b><span>A first view of where money is stuck, by cause, and what your team could clear first.</span></li></ol><div style="margin-top:var(--sp-50)"><div class="contact-line"><span class="kicker">Email</span><a href="mailto:hello@yourdomain.com">hello@yourdomain.com</a></div><div class="contact-line"><span class="kicker">Already a client?</span><a href="<?php echo esc_url( LEXCOLLECT_APP_LOGIN_URL ); ?>">Log in to your workspace</a></div></div></aside></div></div></section><section class="section section--deep section--rule"><div class="container"><div class="split"><div><p class="eyebrow">Before you book</p><h2>Common questions</h2></div><div class="faq"><details open=""><summary><h3>Do we need to be a particular kind of firm?</h3></summary><div><p>No. If your firm bills clients, carries receivables and has someone chasing late accounts, it fits. Tell us what your firm does and which systems you run, and we&#x27;ll tell you honestly how well LexCollect fits.</p></div></details><details><summary><h3>What should we have ready for the call?</h3></summary><div><p>The names of your client-management, payment, accounting and banking systems, plus a rough sense of how many active payment plans or open accounts you carry. No exports are needed for a first conversation.</p></div></details><details><summary><h3>Who from our firm should join?</h3></summary><div><p>Whoever knows where the money goes: usually the owner or managing partner, plus the administrator, controller or bookkeeper.</p></div></details></div></div></div></section>
<!-- /wp:html -->
