#!/usr/bin/env python3
"""
Builds the LexCollect WordPress theme from the React marketing site.

    PRERENDER_TARGET=wp npx vite-node --mode production scripts/prerender-marketing.tsx <fragments-dir>
    python3 scripts/build-wordpress-theme.py <fragments-dir>

Reads the prerendered page fragments (<page>.main.html, header.html,
footer.html), writes them into wordpress/lexcollect/patterns as block-pattern
PHP files, copies src/styles/marketing.css into the theme, and zips the theme
to wordpress/lexcollect.zip for upload (Appearance > Themes > Add New > Upload).
"""
from __future__ import annotations

import re
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
THEME = ROOT / "wordpress" / "lexcollect"
FRAGMENTS = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else ROOT / "dist-wp"

PAGES = {
    # file stem -> (pattern slug, title, description)
    "index": ("page-home", "Home page", "Brand hero, results, pillars, AR Management, Connect, suited-to-your-firm, FAQ, call form and CTA."),
    "about": ("page-about", "About page", "Elite-accounting-department hero with the momentum card, story, outcomes, principles, who we serve and CTA."),
    "platform": ("page-platform", "Platform page", "Eight modules, comparison table, getting started, FAQ and CTA."),
    "results": ("page-results", "Results page", "Wins strip and the seven result stories from the first deployment."),
    "contact": ("page-contact", "Contact page", "Call request form, what happens next, and common questions."),
}

FORM_RE = re.compile(r'<form class="form(?P<card> contact-card)?"[\s\S]*?</form>')
# "Book a call" links point at the contact page in the React build (no booking URL set);
# in WordPress they go through lexcollect_booking_url(), which honours LEXCOLLECT_BOOKING_URL.
CONTACT_HREF = "href=\"<?php echo esc_url( lexcollect_page_url( 'contact' ) ); ?>\""
BOOKING_HREF = "href=\"<?php echo esc_url( lexcollect_booking_url() ); ?>\""
BOOK_CALL_RE = re.compile(re.escape(CONTACT_HREF) + r'([^>]*>\s*Book a call)')


def pattern_header(slug: str, title: str, description: str, categories: str = "lexcollect-pages", extra: str = "") -> str:
    return f"""<?php
/**
 * Title: {title}
 * Slug: lexcollect/{slug}
 * Categories: {categories}
{extra} * Viewport Width: 1400
 * Description: {description}
 *
 * Generated by scripts/build-wordpress-theme.py from the React marketing site.
 * Edit the copy in src/pages and rebuild, or edit this HTML block in WordPress.
 *
 * @package LexCollect
 */

?>
"""


def html_block(html: str) -> str:
    return "<!-- wp:html -->\n" + html.strip() + "\n<!-- /wp:html -->\n"


def booking_links(html: str) -> str:
    return BOOK_CALL_RE.sub(lambda m: BOOKING_HREF + m.group(1), html)


def replace_forms(html: str) -> str:
    """Swap the static React form for the theme's contact-form shortcode."""

    def sub(m: re.Match) -> str:
        heading = ' heading="Request a call"' if m.group("card") else ""
        return (
            "\n<!-- /wp:html -->\n\n"
            f"<!-- wp:shortcode -->\n[lexcollect_contact{heading}]\n<!-- /wp:shortcode -->\n\n"
            "<!-- wp:html -->\n"
        )

    return FORM_RE.sub(sub, html)


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")


def main() -> None:
    if not FRAGMENTS.is_dir():
        sys.exit(f"fragments dir not found: {FRAGMENTS}")

    patterns = THEME / "patterns"

    # Page patterns (one HTML block each, form swapped for the shortcode).
    for stem, (slug, title, desc) in PAGES.items():
        src = FRAGMENTS / f"{stem}.main.html"
        html = src.read_text(encoding="utf-8")
        body = html_block(replace_forms(booking_links(html)))
        extra = " * Block Types: core/post-content\n * Post Types: page\n"
        write(patterns / f"{slug}.php", pattern_header(slug, title, desc, extra=extra) + body)

    # Starter article: just the prose, so the single-post template supplies title and meta.
    post = (FRAGMENTS / "blog-post.main.html").read_text(encoding="utf-8")
    prose = re.search(r'<div class="prose">[\s\S]*?</div>\s*</div>\s*</article>', post)
    if not prose:
        sys.exit("could not find article prose in blog-post.main.html")
    prose_html = prose.group(0).rsplit("</div>", 2)[0] + "</div>"
    write(
        patterns / "post-article.php",
        pattern_header(
            "post-article",
            "Starter article",
            "Where Firms Lose Money Between Their Systems and the Bank. Saved as a draft post by LexCollect setup.",
            categories="lexcollect",
            extra=" * Inserter: no\n",
        )
        + html_block(prose_html),
    )

    # Header and footer, used by every template through parts/header.html and parts/footer.html.
    header = booking_links((FRAGMENTS / "header.html").read_text(encoding="utf-8"))
    footer = booking_links((FRAGMENTS / "footer.html").read_text(encoding="utf-8"))
    write(
        patterns / "header.php",
        pattern_header("header", "Header", "Logo lockup, main menu, Log in link and the Book a call button.", categories="header", extra=" * Block Types: core/template-part/header\n * Inserter: no\n")
        + html_block(header),
    )
    write(
        patterns / "footer.php",
        pattern_header("footer", "Footer", "Brand lockup, three link columns and a legal bar.", categories="lexcollect, footer", extra=" * Block Types: core/template-part/footer\n * Inserter: no\n")
        + html_block(footer),
    )

    # Stylesheet and the small script the site needs (mobile menu, blog filter chips).
    css = (ROOT / "src" / "styles" / "marketing.css").read_text(encoding="utf-8")
    css += """
/* ---------- WordPress adjustments ---------- */
body.lc { padding-left: 0 !important; padding-right: 0 !important; }
.admin-bar .lc .site-header { top: 32px; }
@media (max-width: 782px) { .admin-bar .lc .site-header { top: 46px; } }
.lc .wp-block-post-content > * { max-width: none; }
"""
    write(THEME / "assets" / "css" / "marketing.css", css)
    # The page interactions (src/lib/marketing-site.ts, shared with the React site)
    # plus the WordPress-only menu and blog chips, bundled to one plain script.
    esbuild = ROOT / "node_modules" / ".bin" / ("esbuild.cmd" if sys.platform == "win32" else "esbuild")
    out_js = THEME / "assets" / "js" / "site.js"
    subprocess.run(
        [
            str(esbuild),
            str(ROOT / "scripts" / "wp-site-entry.ts"),
            "--bundle",
            "--format=iife",
            "--target=es2018",
            f"--outfile={out_js}",
            "--banner:js=/* LexCollect site script. Generated by scripts/build-wordpress-theme.py from src/lib/marketing-site.ts; do not edit. */",
        ],
        check=True,
    )
    print(f"wrote {out_js.relative_to(ROOT)}")

    # Zip for upload.
    zip_path = ROOT / "wordpress" / "lexcollect.zip"
    if zip_path.exists():
        zip_path.unlink()
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for file in sorted(THEME.rglob("*")):
            if file.is_file() and "__pycache__" not in file.parts:
                zf.write(file, Path("lexcollect") / file.relative_to(THEME))
    print(f"zipped -> {zip_path.relative_to(ROOT)} ({zip_path.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
