// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbrufeewsisljtoegops.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFicnVmZWV3c2lzbGp0b2Vnb3BzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwNjY1MzAsImV4cCI6MjA4ODY0MjUzMH0.JI0cKKy_qDVzNBNsHlt4vDj0rZ2Kp7naNiCrvliNiD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});